INSERT INTO countries (name) VALUES ('Albania');
INSERT INTO countries (name) VALUES ('Andorra');
INSERT INTO countries (name) VALUES ('Armenia');
INSERT INTO countries (name) VALUES ('Austria');
INSERT INTO countries (name) VALUES ('Azerbaijan');
INSERT INTO countries (name) VALUES ('Belarus');
INSERT INTO countries (name) VALUES ('Belgium');
INSERT INTO countries (name) VALUES ('Bosnia and Herzegovina');
INSERT INTO countries (name) VALUES ('Bulgaria');
INSERT INTO countries (name) VALUES ('Croatia');
INSERT INTO countries (name) VALUES ('Cyprus');
INSERT INTO countries (name) VALUES ('Czech Republic');
INSERT INTO countries (name) VALUES ('Denmark');
INSERT INTO countries (name) VALUES ('Estonia');
INSERT INTO countries (name) VALUES ('Finland');
INSERT INTO countries (name) VALUES ('France');
INSERT INTO countries (name) VALUES ('Georgia');
INSERT INTO countries (name) VALUES ('Germany');
INSERT INTO countries (name) VALUES ('Greece');
INSERT INTO countries (name) VALUES ('Hungary');
INSERT INTO countries (name) VALUES ('Iceland');
INSERT INTO countries (name) VALUES ('Ireland');
INSERT INTO countries (name) VALUES ('Italy');
INSERT INTO countries (name) VALUES ('Kazakhstan');
INSERT INTO countries (name) VALUES ('Kosovo');
INSERT INTO countries (name) VALUES ('Latvia');
INSERT INTO countries (name) VALUES ('Liechtenstein');
INSERT INTO countries (name) VALUES ('Lithuania');
INSERT INTO countries (name) VALUES ('Luxembourg');
INSERT INTO countries (name) VALUES ('Malta');
INSERT INTO countries (name) VALUES ('Moldova');
INSERT INTO countries (name) VALUES ('Monaco');
INSERT INTO countries (name) VALUES ('Montenegro');
INSERT INTO countries (name) VALUES ('Netherlands');
INSERT INTO countries (name) VALUES ('North Macedonia');
INSERT INTO countries (name) VALUES ('Norway');
INSERT INTO countries (name) VALUES ('Poland');
INSERT INTO countries (name) VALUES ('Portugal');
INSERT INTO countries (name) VALUES ('Romania');
INSERT INTO countries (name) VALUES ('Russia');
INSERT INTO countries (name) VALUES ('San Marino');
INSERT INTO countries (name) VALUES ('Serbia');
INSERT INTO countries (name) VALUES ('Slovakia');
INSERT INTO countries (name) VALUES ('Slovenia');
INSERT INTO countries (name) VALUES ('Spain');
INSERT INTO countries (name) VALUES ('Sweden');
INSERT INTO countries (name) VALUES ('Switzerland');
INSERT INTO countries (name) VALUES ('Turkey');
INSERT INTO countries (name) VALUES ('Ukraine');
INSERT INTO countries (name) VALUES ('United Kingdom');
INSERT INTO countries (name) VALUES ('Vatican City');